// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_AppDesktop;
lv_obj_t * ui_AppPanel1;
lv_obj_t * ui_ButtonFall;
lv_obj_t * ui_ButtonSteps;
lv_obj_t * ui_ButtonInactivity;
lv_obj_t * ui_ArcPedometer;
lv_obj_t * ui_ArcInactivity;
lv_obj_t * ui_ArcFall;
lv_obj_t * ui_AppFall;
lv_obj_t * ui_PanelFall;
lv_obj_t * ui_LabelFallDetect;
lv_obj_t * ui_SwitchFallDetection;
lv_obj_t * ui_ArcFalldetection;
lv_obj_t * ui_LabelFallcount;
lv_obj_t * ui_FallcountChart;
lv_obj_t * ui_AppPedometer;
lv_obj_t * ui_PanelPedometer;
lv_obj_t * ui_Pedometer;
lv_obj_t * ui_SwitchPedometer;
lv_obj_t * ui_ArcSteps;
lv_obj_t * ui_LabelStepcount;
lv_obj_t * ui_StepcountChart;
lv_obj_t * ui_AppInactivity;
lv_obj_t * ui_PanelInactivity;
lv_obj_t * ui_InactivityDetection;
lv_obj_t * ui_SwitchInactivity;
lv_obj_t * ui_ArcInactivitycount;
lv_obj_t * ui_ChartInactivity;
lv_obj_t * ui_LabelInactivitycount;
lv_obj_t * ui_AppTestpage;
lv_obj_t * ui_PanelMPU;
lv_obj_t * ui_LabelMPUYAW;
lv_obj_t * ui_LabelMPURoll;
lv_obj_t * ui_LabelMPUPitch;
lv_obj_t * ui_LabelMPUAS;
lv_obj_t * ui_LabelMPUSteps;
lv_obj_t * ui_ImageBattery;
lv_obj_t * ui_LabelTime;
lv_obj_t * ui_ImageBatterybar;
lv_obj_t * ui_BatteryBar;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS


///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void Panel_ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
