// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "../src/ChappieUI/Launcher/UI/ui.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_AppDesktop;
extern lv_obj_t * ui_AppPanel1;
extern lv_obj_t * ui_ButtonFall;
extern lv_obj_t * ui_ButtonSteps;
extern lv_obj_t * ui_ButtonInactivity;
extern lv_obj_t * ui_ArcPedometer;
extern lv_obj_t * ui_ArcInactivity;
extern lv_obj_t * ui_ArcFall;
extern lv_obj_t * ui_AppFall;
extern lv_obj_t * ui_PanelFall;
extern lv_obj_t * ui_LabelFallDetect;
extern lv_obj_t * ui_SwitchFallDetection;
extern lv_obj_t * ui_ArcFalldetection;
extern lv_obj_t * ui_LabelFallcount;
extern lv_obj_t * ui_FallcountChart;
extern lv_obj_t * ui_AppPedometer;
extern lv_obj_t * ui_PanelPedometer;
extern lv_obj_t * ui_Pedometer;
extern lv_obj_t * ui_SwitchPedometer;
extern lv_obj_t * ui_ArcSteps;
extern lv_obj_t * ui_LabelStepcount;
extern lv_obj_t * ui_StepcountChart;
extern lv_obj_t * ui_AppInactivity;
extern lv_obj_t * ui_PanelInactivity;
extern lv_obj_t * ui_InactivityDetection;
extern lv_obj_t * ui_SwitchInactivity;
extern lv_obj_t * ui_ArcInactivitycount;
extern lv_obj_t * ui_ChartInactivity;
extern lv_obj_t * ui_LabelInactivitycount;
extern lv_obj_t * ui_AppTestpage;
extern lv_obj_t * ui_PanelMPU;
extern lv_obj_t * ui_LabelMPUYAW;
extern lv_obj_t * ui_LabelMPURoll;
extern lv_obj_t * ui_LabelMPUPitch;
extern lv_obj_t * ui_LabelMPUAS;
extern lv_obj_t * ui_LabelMPUSteps;
extern lv_obj_t * ui_ImageBattery;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_ImageBatterybar;
extern lv_obj_t * ui_BatteryBar;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_img_falldown_png);    // assets/IMG_Falldown.png
LV_IMG_DECLARE(ui_img_img_steps_png);    // assets/IMG_Steps.png
LV_IMG_DECLARE(ui_img_img_inactivity_png);    // assets/IMG_Inactivity.png


// FONTS


// UI INIT
void Panel_ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
