// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
lv_coord_t ui_FallcountChart_series_1_array[] = { 0, 0, 0, 1, 0, 2, 4, 1, 0, 0 };
lv_coord_t ui_StepcountChart_series_1_array[] = { 300, 1000, 1010, 2050, 5000, 6401, 560};
lv_coord_t ui_ChartInactivity_series_1_array[] = { 0, 0, 0, 1, 0, 2, 4, 1, 0, 0 };
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AppDesktop = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_AppDesktop, 280);
    lv_obj_set_height(ui_AppDesktop, 240);
    lv_obj_set_align(ui_AppDesktop, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_AppDesktop, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_AppDesktop, LV_DIR_VER);
    lv_obj_set_style_radius(ui_AppDesktop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AppDesktop, lv_color_hex(0x4D5B74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AppDesktop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AppDesktop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AppDesktop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AppPanel1 = lv_obj_create(ui_AppDesktop);
    lv_obj_set_width(ui_AppPanel1, 280);
    lv_obj_set_height(ui_AppPanel1, 240);
    lv_obj_set_align(ui_AppPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AppPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_AppPanel1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_AppPanel1, LV_DIR_VER);
    lv_obj_set_style_radius(ui_AppPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AppPanel1, lv_color_hex(0x4D5B74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AppPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AppPanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AppPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonFall = lv_btn_create(ui_AppPanel1);
    lv_obj_set_width(ui_ButtonFall, 60);
    lv_obj_set_height(ui_ButtonFall, 60);
    lv_obj_set_x(ui_ButtonFall, -90);
    lv_obj_set_y(ui_ButtonFall, -80);
    lv_obj_set_align(ui_ButtonFall, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonFall, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonFall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonFall, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonFall, lv_color_hex(0xA6B4CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonFall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonFall, &ui_img_img_falldown_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ButtonFall, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonFall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonFall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonFall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonFall, lv_color_hex(0xE65454), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonFall, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ButtonSteps = lv_btn_create(ui_AppPanel1);
    lv_obj_set_width(ui_ButtonSteps, 60);
    lv_obj_set_height(ui_ButtonSteps, 60);
    lv_obj_set_x(ui_ButtonSteps, -90);
    lv_obj_set_y(ui_ButtonSteps, 0);
    lv_obj_set_align(ui_ButtonSteps, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSteps, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSteps, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonSteps, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonSteps, lv_color_hex(0xA6B4CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSteps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonSteps, &ui_img_img_steps_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ButtonSteps, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonSteps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonSteps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonSteps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonSteps, lv_color_hex(0x8BEF97), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonSteps, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ButtonInactivity = lv_btn_create(ui_AppPanel1);
    lv_obj_set_width(ui_ButtonInactivity, 60);
    lv_obj_set_height(ui_ButtonInactivity, 60);
    lv_obj_set_x(ui_ButtonInactivity, -90);
    lv_obj_set_y(ui_ButtonInactivity, 80);
    lv_obj_set_align(ui_ButtonInactivity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonInactivity, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonInactivity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonInactivity, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonInactivity, lv_color_hex(0xA6B4CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonInactivity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonInactivity, &ui_img_img_inactivity_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ButtonInactivity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonInactivity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonInactivity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonInactivity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonInactivity, lv_color_hex(0x6DA1FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonInactivity, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ArcPedometer = lv_arc_create(ui_AppPanel1);
    lv_obj_set_width(ui_ArcPedometer, 150);
    lv_obj_set_height(ui_ArcPedometer, 150);
    lv_obj_set_x(ui_ArcPedometer, 42);
    lv_obj_set_y(ui_ArcPedometer, -1);
    lv_obj_set_align(ui_ArcPedometer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcPedometer, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_ArcPedometer, 0, 10000);
    lv_arc_set_value(ui_ArcPedometer, 2340);
    lv_arc_set_bg_angles(ui_ArcPedometer, 0, 360);
    lv_obj_set_style_arc_color(ui_ArcPedometer, lv_color_hex(0x2B492F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcPedometer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcPedometer, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcPedometer, lv_color_hex(0x8BEF97), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcPedometer, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcPedometer, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcPedometer, lv_color_hex(0x8BEF97), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcPedometer, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ArcPedometer, lv_color_hex(0x2B492F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ArcPedometer, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ArcPedometer, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ArcPedometer, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcPedometer, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcPedometer, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcPedometer, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcPedometer, 3, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcInactivity = lv_arc_create(ui_AppPanel1);
    lv_obj_set_width(ui_ArcInactivity, 150);
    lv_obj_set_height(ui_ArcInactivity, 121);
    lv_obj_set_x(ui_ArcInactivity, 57);
    lv_obj_set_y(ui_ArcInactivity, -1);
    lv_obj_set_align(ui_ArcInactivity, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcInactivity, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_ArcInactivity, 0, 5);
    lv_arc_set_value(ui_ArcInactivity, 1);
    lv_arc_set_bg_angles(ui_ArcInactivity, 0, 360);
    lv_obj_set_style_shadow_color(ui_ArcInactivity, lv_color_hex(0x6DA1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ArcInactivity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_ArcInactivity, lv_color_hex(0x213251), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcInactivity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcInactivity, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcInactivity, lv_color_hex(0x6DA1FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcInactivity, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcInactivity, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcInactivity, lv_color_hex(0x6DA1FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcInactivity, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ArcInactivity, lv_color_hex(0x213251), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ArcInactivity, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ArcInactivity, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ArcInactivity, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcInactivity, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcInactivity, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcInactivity, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcInactivity, 3, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcFall = lv_arc_create(ui_AppPanel1);
    lv_obj_set_width(ui_ArcFall, 150);
    lv_obj_set_height(ui_ArcFall, 91);
    lv_obj_set_x(ui_ArcFall, 72);
    lv_obj_set_y(ui_ArcFall, -1);
    lv_obj_set_align(ui_ArcFall, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcFall, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_ArcFall, LV_SCROLLBAR_MODE_OFF);
    lv_arc_set_range(ui_ArcFall, 0, 5);
    lv_arc_set_value(ui_ArcFall, 2);
    lv_arc_set_bg_angles(ui_ArcFall, 0, 360);
    lv_obj_set_style_arc_color(ui_ArcFall, lv_color_hex(0x602222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcFall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcFall, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcFall, lv_color_hex(0xE65454), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcFall, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcFall, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcFall, lv_color_hex(0xE65454), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcFall, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ArcFall, lv_color_hex(0x602222), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ArcFall, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ArcFall, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ArcFall, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcFall, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcFall, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcFall, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcFall, 3, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_AppFall = lv_obj_create(ui_AppDesktop);
    lv_obj_set_width(ui_AppFall, 280);
    lv_obj_set_height(ui_AppFall, 240);
    lv_obj_set_x(ui_AppFall, 0);
    lv_obj_set_y(ui_AppFall, 240);
    lv_obj_set_align(ui_AppFall, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AppFall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_AppFall, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_AppFall, LV_DIR_VER);
    lv_obj_set_style_radius(ui_AppFall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AppFall, lv_color_hex(0x4D5B74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AppFall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AppFall, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AppFall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelFall = lv_obj_create(ui_AppFall);
    lv_obj_set_width(ui_PanelFall, 240);
    lv_obj_set_height(ui_PanelFall, 90);
    lv_obj_set_x(ui_PanelFall, -2);
    lv_obj_set_y(ui_PanelFall, -38);
    lv_obj_set_align(ui_PanelFall, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelFall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelFall, lv_color_hex(0xA6B4CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelFall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFallDetect = lv_label_create(ui_PanelFall);
    lv_obj_set_width(ui_LabelFallDetect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFallDetect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFallDetect, 57);
    lv_obj_set_y(ui_LabelFallDetect, -23);
    lv_obj_set_align(ui_LabelFallDetect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFallDetect, "FallDetect");

    ui_SwitchFallDetection = lv_switch_create(ui_PanelFall);
    lv_obj_set_width(ui_SwitchFallDetection, 50);
    lv_obj_set_height(ui_SwitchFallDetection, 25);
    lv_obj_set_x(ui_SwitchFallDetection, 56);
    lv_obj_set_y(ui_SwitchFallDetection, 13);
    lv_obj_set_align(ui_SwitchFallDetection, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SwitchFallDetection, lv_color_hex(0x602222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchFallDetection, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_ArcFalldetection = lv_arc_create(ui_PanelFall);
    lv_obj_set_width(ui_ArcFalldetection, 80);
    lv_obj_set_height(ui_ArcFalldetection, 76);
    lv_obj_set_x(ui_ArcFalldetection, -60);
    lv_obj_set_y(ui_ArcFalldetection, 0);
    lv_obj_set_align(ui_ArcFalldetection, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcFalldetection, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_ArcFalldetection, 0, 5);
    lv_arc_set_value(ui_ArcFalldetection, 2);
    lv_arc_set_bg_angles(ui_ArcFalldetection, 0, 360);
    lv_obj_set_style_arc_color(ui_ArcFalldetection, lv_color_hex(0x602222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcFalldetection, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcFalldetection, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcFalldetection, lv_color_hex(0xE65454), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcFalldetection, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcFalldetection, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcFalldetection, lv_color_hex(0xE65454), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcFalldetection, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ArcFalldetection, lv_color_hex(0x602222), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ArcFalldetection, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ArcFalldetection, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ArcFalldetection, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcFalldetection, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcFalldetection, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcFalldetection, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcFalldetection, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelFallcount = lv_label_create(ui_PanelFall);
    lv_obj_set_width(ui_LabelFallcount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFallcount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFallcount, -62);
    lv_obj_set_y(ui_LabelFallcount, 1);
    lv_obj_set_align(ui_LabelFallcount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFallcount, "2");
    lv_obj_set_style_text_font(ui_LabelFallcount, &ui_font_FontUbuntuBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FallcountChart = lv_chart_create(ui_AppFall);
    lv_obj_set_width(ui_FallcountChart, 235);
    lv_obj_set_height(ui_FallcountChart, 77);
    lv_obj_set_x(ui_FallcountChart, -2);
    lv_obj_set_y(ui_FallcountChart, 58);
    lv_obj_set_align(ui_FallcountChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_FallcountChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_FallcountChart, 7);
    lv_chart_set_range(ui_FallcountChart, LV_CHART_AXIS_PRIMARY_Y, 0, 5);
    lv_chart_set_div_line_count(ui_FallcountChart, 6, 7);
    lv_chart_set_axis_tick(ui_FallcountChart, LV_CHART_AXIS_PRIMARY_X, 5, 7, 7, 1, false, 50);
    lv_chart_set_axis_tick(ui_FallcountChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 6, 1, true, 50);
    lv_chart_set_axis_tick(ui_FallcountChart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_chart_series_t * ui_FallcountChart_series_1 = lv_chart_add_series(ui_FallcountChart, lv_color_hex(0x808080),
                                                                         LV_CHART_AXIS_PRIMARY_Y);
    //static lv_coord_t ui_FallcountChart_series_1_array[] = { 0, 0, 0, 1, 0, 2, 4, 1, 0, 0 };
    lv_chart_set_ext_y_array(ui_FallcountChart, ui_FallcountChart_series_1, ui_FallcountChart_series_1_array);
    lv_obj_set_style_bg_color(ui_FallcountChart, lv_color_hex(0xA6B4CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FallcountChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_FallcountChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_FallcountChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_AppPedometer = lv_obj_create(ui_AppDesktop);
    lv_obj_set_width(ui_AppPedometer, 280);
    lv_obj_set_height(ui_AppPedometer, 240);
    lv_obj_set_x(ui_AppPedometer, 0);
    lv_obj_set_y(ui_AppPedometer, 480);
    lv_obj_set_align(ui_AppPedometer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AppPedometer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_AppPedometer, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_AppPedometer, LV_DIR_VER);
    lv_obj_set_style_radius(ui_AppPedometer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AppPedometer, lv_color_hex(0x4D5B74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AppPedometer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AppPedometer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AppPedometer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPedometer = lv_obj_create(ui_AppPedometer);
    lv_obj_set_width(ui_PanelPedometer, 240);
    lv_obj_set_height(ui_PanelPedometer, 90);
    lv_obj_set_x(ui_PanelPedometer, -2);
    lv_obj_set_y(ui_PanelPedometer, -38);
    lv_obj_set_align(ui_PanelPedometer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPedometer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPedometer, lv_color_hex(0xA6B4CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPedometer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pedometer = lv_label_create(ui_PanelPedometer);
    lv_obj_set_width(ui_Pedometer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pedometer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pedometer, 57);
    lv_obj_set_y(ui_Pedometer, -23);
    lv_obj_set_align(ui_Pedometer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pedometer, "Pedometer");
    lv_obj_set_style_text_font(ui_Pedometer, &ui_font_FontUbuntuBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchPedometer = lv_switch_create(ui_PanelPedometer);
    lv_obj_set_width(ui_SwitchPedometer, 50);
    lv_obj_set_height(ui_SwitchPedometer, 25);
    lv_obj_set_x(ui_SwitchPedometer, 57);
    lv_obj_set_y(ui_SwitchPedometer, 13);
    lv_obj_set_align(ui_SwitchPedometer, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SwitchPedometer, lv_color_hex(0x2B492F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchPedometer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SwitchPedometer, lv_color_hex(0x8BEF97), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_SwitchPedometer, lv_color_hex(0x8BEF97), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_SwitchPedometer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_recolor(ui_SwitchPedometer, lv_color_hex(0x8BEF97), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_SwitchPedometer, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ArcSteps = lv_arc_create(ui_PanelPedometer);
    lv_obj_set_width(ui_ArcSteps, 80);
    lv_obj_set_height(ui_ArcSteps, 76);
    lv_obj_set_x(ui_ArcSteps, -60);
    lv_obj_set_y(ui_ArcSteps, 0);
    lv_obj_set_align(ui_ArcSteps, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcSteps, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_ArcSteps, 0, 10000);
    lv_arc_set_value(ui_ArcSteps, 2540);
    lv_arc_set_bg_angles(ui_ArcSteps, 0, 360);
    lv_obj_set_style_arc_color(ui_ArcSteps, lv_color_hex(0x2B492F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSteps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcSteps, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcSteps, lv_color_hex(0x8BEF97), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSteps, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcSteps, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcSteps, lv_color_hex(0x8BEF97), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcSteps, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ArcSteps, lv_color_hex(0x2B492F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ArcSteps, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ArcSteps, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ArcSteps, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcSteps, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcSteps, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcSteps, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcSteps, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelStepcount = lv_label_create(ui_PanelPedometer);
    lv_obj_set_width(ui_LabelStepcount, 46);
    lv_obj_set_height(ui_LabelStepcount, 17);
    lv_obj_set_x(ui_LabelStepcount, -62);
    lv_obj_set_y(ui_LabelStepcount, 1);
    lv_obj_set_align(ui_LabelStepcount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStepcount, "10000");
    lv_obj_set_style_text_font(ui_LabelStepcount, &ui_font_FontUbuntuBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StepcountChart = lv_chart_create(ui_AppPedometer);
    lv_obj_set_width(ui_StepcountChart, 187);
    lv_obj_set_height(ui_StepcountChart, 77);
    lv_obj_set_x(ui_StepcountChart, -1);
    lv_obj_set_y(ui_StepcountChart, 64);
    lv_obj_set_align(ui_StepcountChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_StepcountChart, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_StepcountChart, 7);
    lv_chart_set_range(ui_StepcountChart, LV_CHART_AXIS_PRIMARY_Y, 1000, 10000);
    lv_chart_set_range(ui_StepcountChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_StepcountChart, 6, 0);
    lv_chart_set_axis_tick(ui_StepcountChart, LV_CHART_AXIS_PRIMARY_X, 5, 7, 7, 1, false, 50);
    lv_chart_set_axis_tick(ui_StepcountChart, LV_CHART_AXIS_PRIMARY_Y, 1, 1000, 6, 1, true, 2);
    lv_chart_set_axis_tick(ui_StepcountChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_StepcountChart_series_1 = lv_chart_add_series(ui_StepcountChart, lv_color_hex(0x808080),
                                                                         LV_CHART_AXIS_PRIMARY_Y);
    //static lv_coord_t ui_StepcountChart_series_1_array[] = { 300, 1000, 1010, 2050, 5000, 6401, 560 };
    lv_chart_set_ext_y_array(ui_StepcountChart, ui_StepcountChart_series_1, ui_StepcountChart_series_1_array);
    lv_obj_set_style_bg_color(ui_StepcountChart, lv_color_hex(0xA6B4CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StepcountChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_StepcountChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_StepcountChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_AppInactivity = lv_obj_create(ui_AppDesktop);
    lv_obj_set_width(ui_AppInactivity, 280);
    lv_obj_set_height(ui_AppInactivity, 240);
    lv_obj_set_x(ui_AppInactivity, 0);
    lv_obj_set_y(ui_AppInactivity, 720);
    lv_obj_set_align(ui_AppInactivity, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AppInactivity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_AppInactivity, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_AppInactivity, LV_DIR_VER);
    lv_obj_set_style_radius(ui_AppInactivity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AppInactivity, lv_color_hex(0x4D5B74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AppInactivity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AppInactivity, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AppInactivity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelInactivity = lv_obj_create(ui_AppInactivity);
    lv_obj_set_width(ui_PanelInactivity, 240);
    lv_obj_set_height(ui_PanelInactivity, 90);
    lv_obj_set_x(ui_PanelInactivity, -2);
    lv_obj_set_y(ui_PanelInactivity, -38);
    lv_obj_set_align(ui_PanelInactivity, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelInactivity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelInactivity, lv_color_hex(0xA6B4CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelInactivity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InactivityDetection = lv_label_create(ui_PanelInactivity);
    lv_obj_set_width(ui_InactivityDetection, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InactivityDetection, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InactivityDetection, 57);
    lv_obj_set_y(ui_InactivityDetection, -23);
    lv_obj_set_align(ui_InactivityDetection, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InactivityDetection, "Inactivity");

    ui_SwitchInactivity = lv_switch_create(ui_PanelInactivity);
    lv_obj_set_width(ui_SwitchInactivity, 50);
    lv_obj_set_height(ui_SwitchInactivity, 25);
    lv_obj_set_x(ui_SwitchInactivity, 57);
    lv_obj_set_y(ui_SwitchInactivity, 13);
    lv_obj_set_align(ui_SwitchInactivity, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SwitchInactivity, lv_color_hex(0x213251), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchInactivity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_recolor(ui_SwitchInactivity, lv_color_hex(0x8BEF97), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_SwitchInactivity, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ArcInactivitycount = lv_arc_create(ui_PanelInactivity);
    lv_obj_set_width(ui_ArcInactivitycount, 80);
    lv_obj_set_height(ui_ArcInactivitycount, 76);
    lv_obj_set_x(ui_ArcInactivitycount, -60);
    lv_obj_set_y(ui_ArcInactivitycount, 0);
    lv_obj_set_align(ui_ArcInactivitycount, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcInactivitycount, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_ArcInactivitycount, 0, 5);
    lv_arc_set_value(ui_ArcInactivitycount, 2);
    lv_arc_set_bg_angles(ui_ArcInactivitycount, 0, 360);
    lv_obj_set_style_arc_color(ui_ArcInactivitycount, lv_color_hex(0x213251), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcInactivitycount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcInactivitycount, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcInactivitycount, lv_color_hex(0x6DA1FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcInactivitycount, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcInactivitycount, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcInactivitycount, lv_color_hex(0x6DA1FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcInactivitycount, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ArcInactivitycount, lv_color_hex(0x213251), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ArcInactivitycount, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ArcInactivitycount, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ArcInactivitycount, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcInactivitycount, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcInactivitycount, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcInactivitycount, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcInactivitycount, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ChartInactivity = lv_chart_create(ui_AppInactivity);
    lv_obj_set_width(ui_ChartInactivity, 235);
    lv_obj_set_height(ui_ChartInactivity, 77);
    lv_obj_set_x(ui_ChartInactivity, -2);
    lv_obj_set_y(ui_ChartInactivity, 58);
    lv_obj_set_align(ui_ChartInactivity, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartInactivity, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartInactivity, 7);
    lv_chart_set_range(ui_ChartInactivity, LV_CHART_AXIS_PRIMARY_Y, 0, 5);
    lv_chart_set_range(ui_ChartInactivity, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_ChartInactivity, 6, 7);
    lv_chart_set_axis_tick(ui_ChartInactivity, LV_CHART_AXIS_PRIMARY_X, 5, 7, 7, 1, false, 50);
    lv_chart_set_axis_tick(ui_ChartInactivity, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 6, 1, true, 50);
    lv_chart_set_axis_tick(ui_ChartInactivity, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_ChartInactivity_series_1 = lv_chart_add_series(ui_ChartInactivity, lv_color_hex(0x808080),
                                                                          LV_CHART_AXIS_PRIMARY_Y);
    //static lv_coord_t ui_ChartInactivity_series_1_array[] = { 0, 0, 0, 1, 0, 2, 4, 1, 0, 0 };
    lv_chart_set_ext_y_array(ui_ChartInactivity, ui_ChartInactivity_series_1, ui_ChartInactivity_series_1_array);
    lv_obj_set_style_bg_color(ui_ChartInactivity, lv_color_hex(0xA6B4CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartInactivity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ChartInactivity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ChartInactivity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_LabelInactivitycount = lv_label_create(ui_AppInactivity);
    lv_obj_set_width(ui_LabelInactivitycount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInactivitycount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInactivitycount, -64);
    lv_obj_set_y(ui_LabelInactivitycount, -38);
    lv_obj_set_align(ui_LabelInactivitycount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelInactivitycount, "2");
    lv_obj_set_style_text_font(ui_LabelInactivitycount, &ui_font_FontUbuntuBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AppTestpage = lv_obj_create(ui_AppDesktop);
    lv_obj_set_width(ui_AppTestpage, 280);
    lv_obj_set_height(ui_AppTestpage, 240);
    lv_obj_set_x(ui_AppTestpage, 0);
    lv_obj_set_y(ui_AppTestpage, 960);
    lv_obj_set_align(ui_AppTestpage, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AppTestpage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_AppTestpage, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_AppTestpage, LV_DIR_VER);
    lv_obj_set_style_radius(ui_AppTestpage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AppTestpage, lv_color_hex(0x4D5B74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AppTestpage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AppTestpage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AppTestpage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelMPU = lv_obj_create(ui_AppTestpage);
    lv_obj_set_width(ui_PanelMPU, 240);
    lv_obj_set_height(ui_PanelMPU, 90);
    lv_obj_set_x(ui_PanelMPU, -2);
    lv_obj_set_y(ui_PanelMPU, -38);
    lv_obj_set_align(ui_PanelMPU, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMPU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelMPU, lv_color_hex(0xA6B4CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMPU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMPUYAW = lv_label_create(ui_PanelMPU);
    lv_obj_set_width(ui_LabelMPUYAW, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMPUYAW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMPUYAW, -90);
    lv_obj_set_y(ui_LabelMPUYAW, -25);
    lv_obj_set_align(ui_LabelMPUYAW, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMPUYAW, "Yaw:");
    lv_obj_set_style_text_font(ui_LabelMPUYAW, &ui_font_FontUbuntuBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMPURoll = lv_label_create(ui_PanelMPU);
    lv_obj_set_width(ui_LabelMPURoll, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMPURoll, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMPURoll, -90);
    lv_obj_set_y(ui_LabelMPURoll, 0);
    lv_obj_set_align(ui_LabelMPURoll, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMPURoll, "Roll:");
    lv_obj_set_style_text_font(ui_LabelMPURoll, &ui_font_FontUbuntuBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMPUPitch = lv_label_create(ui_PanelMPU);
    lv_obj_set_width(ui_LabelMPUPitch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMPUPitch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMPUPitch, -90);
    lv_obj_set_y(ui_LabelMPUPitch, 25);
    lv_obj_set_align(ui_LabelMPUPitch, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMPUPitch, "Pitch:");
    lv_obj_set_style_text_font(ui_LabelMPUPitch, &ui_font_FontUbuntuBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMPUAS = lv_label_create(ui_PanelMPU);
    lv_obj_set_width(ui_LabelMPUAS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMPUAS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMPUAS, 30);
    lv_obj_set_y(ui_LabelMPUAS, -25);
    lv_obj_set_align(ui_LabelMPUAS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMPUAS, "AS:");
    lv_obj_set_style_text_font(ui_LabelMPUAS, &ui_font_FontUbuntuBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMPUSteps = lv_label_create(ui_PanelMPU);
    lv_obj_set_width(ui_LabelMPUSteps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMPUSteps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMPUSteps, 30);
    lv_obj_set_y(ui_LabelMPUSteps, 0);
    lv_obj_set_align(ui_LabelMPUSteps, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMPUSteps, "Steps:");
    lv_obj_set_style_text_font(ui_LabelMPUSteps, &ui_font_FontUbuntuBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBattery = lv_img_create(ui_AppDesktop);
    lv_img_set_src(ui_ImageBattery, &ui_img_img_statebar_png);
    lv_obj_set_width(ui_ImageBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageBattery, 0);
    lv_obj_set_y(ui_ImageBattery, -105);
    lv_obj_set_align(ui_ImageBattery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBattery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTime = lv_label_create(ui_ImageBattery);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 280
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "21:15");
    lv_obj_set_style_text_color(ui_LabelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelTime, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTime, &ui_font_FontUbuntuBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBatterybar = lv_img_create(ui_ImageBattery);
    lv_img_set_src(ui_ImageBatterybar, &ui_img_img_battery_png);
    lv_obj_set_width(ui_ImageBatterybar, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageBatterybar, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_ImageBatterybar, 100);
    lv_obj_set_y(ui_ImageBatterybar, -1);
    lv_obj_set_align(ui_ImageBatterybar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBatterybar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBatterybar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryBar = lv_bar_create(ui_ImageBatterybar);
    lv_bar_set_value(ui_BatteryBar, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBar, 17);
    lv_obj_set_height(ui_BatteryBar, 9);
    lv_obj_set_x(ui_BatteryBar, -2);
    lv_obj_set_y(ui_BatteryBar, 0);
    lv_obj_set_align(ui_BatteryBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BatteryBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBar, lv_color_hex(0x4D5B74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BatteryBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);


}
